version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    depends_on:
      - ml-api

  ml-api:
    build: ./ml-api
    ports:
      - "8000:8000"
    volumes:
      - ./ml-api:/app

  mongo:
    image: mongo
    ports:
      - "27017:27017"
